# coding: utf-8

"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from almanac.api.almanac_api import AlmanacApi


class TestAlmanacApi(unittest.TestCase):
    """AlmanacApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlmanacApi()

    def tearDown(self) -> None:
        pass

    def test_get_agent(self) -> None:
        """Test case for get_agent

        Get Specific Agent
        """
        pass

    def test_get_agents_by_domain(self) -> None:
        """Test case for get_agents_by_domain

        Get Agents By Domain
        """
        pass

    def test_get_domain_record(self) -> None:
        """Test case for get_domain_record

        Get Domain Record
        """
        pass

    def test_get_recently_registered_agents(self) -> None:
        """Test case for get_recently_registered_agents

        Get Recently Registered Agents
        """
        pass

    def test_register_agent(self) -> None:
        """Test case for register_agent

        Register Agent
        """
        pass

    def test_register_agents_batch_v1_almanac_agents_batch_post(self) -> None:
        """Test case for register_agents_batch_v1_almanac_agents_batch_post

        Register Agents Batch
        """
        pass

    def test_search_available_agent_name(self) -> None:
        """Test case for search_available_agent_name

        Search Available Agent Name
        """
        pass

    def test_update_agent_status(self) -> None:
        """Test case for update_agent_status

        Update Agent Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
