# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search_api_client.api.internal_api import InternalApi


class TestInternalApi(unittest.TestCase):
    """InternalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InternalApi()

    def tearDown(self) -> None:
        pass

    def test_is_healthy(self) -> None:
        """Test case for is_healthy

        Liveness Probe
        """
        pass

    def test_is_ready(self) -> None:
        """Test case for is_ready

        Readiness Probe
        """
        pass


if __name__ == '__main__':
    unittest.main()
