# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search_api.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_get_agent_interactions_count(self) -> None:
        """Test case for get_agent_interactions_count

        Get Interaction Counts Of Agent
        """
        pass

    def test_get_agent_search_terms_analytics(self) -> None:
        """Test case for get_agent_search_terms_analytics

        Get Agent Search Term Analytics
        """
        pass

    def test_get_agent_searches_analytics(self) -> None:
        """Test case for get_agent_searches_analytics

        Get Agent Search Analytics
        """
        pass

    def test_get_function_interactions(self) -> None:
        """Test case for get_function_interactions

        Get Recent Interactions Of Function
        """
        pass

    def test_search_agent_by_geolocation(self) -> None:
        """Test case for search_agent_by_geolocation

        Search Agent By Geolocation
        """
        pass

    def test_search_agents(self) -> None:
        """Test case for search_agents

        Search Agents
        """
        pass

    def test_search_functions(self) -> None:
        """Test case for search_functions

        Search Functions
        """
        pass

    def test_select_agent(self) -> None:
        """Test case for select_agent

        Select Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
