# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search_api_client.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_agent_selected(self) -> None:
        """Test case for agent_selected

        Mark Agent Clicked
        """
        pass

    def test_get_agent_interactions(self) -> None:
        """Test case for get_agent_interactions

        Get Interaction Counts Of Agent
        """
        pass

    def test_search_agent(self) -> None:
        """Test case for search_agent

        Search Agents
        """
        pass

    def test_search_agent_by_geolocation(self) -> None:
        """Test case for search_agent_by_geolocation

        Search Agents Geo
        """
        pass


if __name__ == '__main__':
    unittest.main()
