# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search_api.api.agents_api import AgentsApi


class TestAgentsApi(unittest.TestCase):
    """AgentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentsApi()

    def tearDown(self) -> None:
        pass

    def test_check_current_campaign_eligibility(self) -> None:
        """Test case for check_current_campaign_eligibility

        Check Current Campaign Eligibility
        """
        pass

    def test_get_agent_interactions_count(self) -> None:
        """Test case for get_agent_interactions_count

        Get Interaction Counts Of Agent
        """
        pass

    def test_search_agent_by_geolocation(self) -> None:
        """Test case for search_agent_by_geolocation

        Search Agent By Geolocation
        """
        pass

    def test_search_agents(self) -> None:
        """Test case for search_agents

        Search Agents
        """
        pass

    def test_select_agent(self) -> None:
        """Test case for select_agent

        Select Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
