# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search_api.models.search_term_percentage import SearchTermPercentage

class TestSearchTermPercentage(unittest.TestCase):
    """SearchTermPercentage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchTermPercentage:
        """Test SearchTermPercentage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchTermPercentage`
        """
        model = SearchTermPercentage()
        if include_optional:
            return SearchTermPercentage(
                term = '',
                last_24h_percentage = 0.0,
                last_7d_percentage = 0.0,
                last_30d_percentage = 0.0
            )
        else:
            return SearchTermPercentage(
                term = '',
                last_24h_percentage = 0.0,
                last_7d_percentage = 0.0,
                last_30d_percentage = 0.0,
        )
        """

    def testSearchTermPercentage(self):
        """Test SearchTermPercentage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
