# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from search_api_client.api.public_api import PublicApi


class TestPublicApi(unittest.TestCase):
    """PublicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PublicApi()

    def tearDown(self) -> None:
        pass

    def test_agent_selected(self) -> None:
        """Test case for agent_selected

        Mark Agent Clicked
        """
        pass

    def test_get_agent_interactions(self) -> None:
        """Test case for get_agent_interactions

        Get Interaction Counts Of Agent
        """
        pass

    def test_get_agent_search_terms_analytics(self) -> None:
        """Test case for get_agent_search_terms_analytics

        Get Agent Search Term Analytics
        """
        pass

    def test_get_agent_searches_analytics(self) -> None:
        """Test case for get_agent_searches_analytics

        Get Agent Search Analytics
        """
        pass

    def test_get_function_interactions(self) -> None:
        """Test case for get_function_interactions

        Get Recent Interactions Of Function
        """
        pass

    def test_search_agent(self) -> None:
        """Test case for search_agent

        Search Agents
        """
        pass

    def test_search_agent_by_geolocation(self) -> None:
        """Test case for search_agent_by_geolocation

        Search Agents Geo
        """
        pass

    def test_search_functions(self) -> None:
        """Test case for search_functions

        Search Functions
        """
        pass


if __name__ == '__main__':
    unittest.main()
