# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.search.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.IsolatedAsyncioTestCase):
    """AnalyticsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AnalyticsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_agent_search_terms_analytics(self) -> None:
        """Test case for get_agent_search_terms_analytics

        Get Agent Search Term Analytics
        """
        pass

    async def test_get_agent_searches_analytics(self) -> None:
        """Test case for get_agent_searches_analytics

        Get Agent Search Analytics
        """
        pass


if __name__ == '__main__':
    unittest.main()
