# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.search.api.functions_api import FunctionsApi


class TestFunctionsApi(unittest.IsolatedAsyncioTestCase):
    """FunctionsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = FunctionsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_function_interactions(self) -> None:
        """Test case for get_function_interactions

        Get Recent Interactions Of Function
        """
        pass

    async def test_search_functions(self) -> None:
        """Test case for search_functions

        Search Functions
        """
        pass


if __name__ == '__main__':
    unittest.main()
