# coding: utf-8

# flake8: noqa
"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from agentverse_client.almanac.models.agent import Agent
from agentverse_client.almanac.models.agent_endpoint import AgentEndpoint
from agentverse_client.almanac.models.agent_registration_attestation import AgentRegistrationAttestation
from agentverse_client.almanac.models.agent_registration_attestation_batch import AgentRegistrationAttestationBatch
from agentverse_client.almanac.models.agent_registration_attestation_metadata_value import AgentRegistrationAttestationMetadataValue
from agentverse_client.almanac.models.agent_status import AgentStatus
from agentverse_client.almanac.models.agent_status_update import AgentStatusUpdate
from agentverse_client.almanac.models.almanac_usage import AlmanacUsage
from agentverse_client.almanac.models.http_validation_error import HTTPValidationError
from agentverse_client.almanac.models.handle_availability_request import HandleAvailabilityRequest
from agentverse_client.almanac.models.handle_availability_response import HandleAvailabilityResponse
from agentverse_client.almanac.models.handle_generate_response import HandleGenerateResponse
from agentverse_client.almanac.models.handle_response import HandleResponse
from agentverse_client.almanac.models.interaction import Interaction
from agentverse_client.almanac.models.interaction_type import InteractionType
from agentverse_client.almanac.models.location_inner import LocationInner
from agentverse_client.almanac.models.manifest import Manifest
from agentverse_client.almanac.models.metadata import Metadata
from agentverse_client.almanac.models.model import Model
from agentverse_client.almanac.models.new_handle_request import NewHandleRequest
from agentverse_client.almanac.models.resolved_protocol_digest import ResolvedProtocolDigest
from agentverse_client.almanac.models.validation_error import ValidationError
