# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.async_search.api.search_api import SearchApi


class TestSearchApi(unittest.IsolatedAsyncioTestCase):
    """SearchApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SearchApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_check_current_campaign_eligibility(self) -> None:
        """Test case for check_current_campaign_eligibility

        Check Current Campaign Eligibility
        """
        pass

    async def test_get_agent_interactions_count(self) -> None:
        """Test case for get_agent_interactions_count

        Get Interaction Counts Of Agent
        """
        pass

    async def test_get_agent_search_terms_analytics(self) -> None:
        """Test case for get_agent_search_terms_analytics

        Get Agent Search Term Analytics
        """
        pass

    async def test_get_agent_searches_analytics(self) -> None:
        """Test case for get_agent_searches_analytics

        Get Agent Search Analytics
        """
        pass

    async def test_get_function_interactions(self) -> None:
        """Test case for get_function_interactions

        Get Recent Interactions Of Function
        """
        pass

    async def test_search_agent_by_geolocation(self) -> None:
        """Test case for search_agent_by_geolocation

        Search Agent By Geolocation
        """
        pass

    async def test_search_agent_tags(self) -> None:
        """Test case for search_agent_tags

        Search Agent Tags
        """
        pass

    async def test_search_agents(self) -> None:
        """Test case for search_agents

        Search Agents
        """
        pass

    async def test_search_functions(self) -> None:
        """Test case for search_functions

        Search Functions
        """
        pass

    async def test_select_agent(self) -> None:
        """Test case for select_agent

        Select Agent
        """
        pass


if __name__ == '__main__':
    unittest.main()
