# coding: utf-8

"""
    Agent Hosting API

      ## Overview  The Agent Hosting API helps users deploy agents to the cloud  ## Authentication  The entire API requires that the user authenticate with the ecosystem first before accessing the api 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from agentverse_client.hosting.aio.models.agent_metadata import AgentMetadata
from typing import Optional, Set
from typing_extensions import Self

class AgentV2(BaseModel):
    """
    Agent model for v2 API - excludes profile fields (name, domain, readme, avatar_url, short_description).
    """ # noqa: E501
    address: StrictStr = Field(description="Bech32 address of the agent.")
    running: StrictBool = Field(description="Whether the agent is currently running.")
    compiled: Optional[StrictBool] = None
    code_digest: Optional[StrictStr] = None
    wallet_address: Optional[StrictStr] = None
    code_update_timestamp: Optional[datetime] = None
    creation_timestamp: Optional[datetime] = None
    revision: Optional[StrictInt] = Field(default=0, description="Revision number of the agent.")
    metadata: Optional[AgentMetadata] = None
    __properties: ClassVar[List[str]] = ["address", "running", "compiled", "code_digest", "wallet_address", "code_update_timestamp", "creation_timestamp", "revision", "metadata"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # set to None if compiled (nullable) is None
        # and model_fields_set contains the field
        if self.compiled is None and "compiled" in self.model_fields_set:
            _dict['compiled'] = None

        # set to None if code_digest (nullable) is None
        # and model_fields_set contains the field
        if self.code_digest is None and "code_digest" in self.model_fields_set:
            _dict['code_digest'] = None

        # set to None if wallet_address (nullable) is None
        # and model_fields_set contains the field
        if self.wallet_address is None and "wallet_address" in self.model_fields_set:
            _dict['wallet_address'] = None

        # set to None if code_update_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.code_update_timestamp is None and "code_update_timestamp" in self.model_fields_set:
            _dict['code_update_timestamp'] = None

        # set to None if creation_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.creation_timestamp is None and "creation_timestamp" in self.model_fields_set:
            _dict['creation_timestamp'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "running": obj.get("running"),
            "compiled": obj.get("compiled"),
            "code_digest": obj.get("code_digest"),
            "wallet_address": obj.get("wallet_address"),
            "code_update_timestamp": obj.get("code_update_timestamp"),
            "creation_timestamp": obj.get("creation_timestamp"),
            "revision": obj.get("revision") if obj.get("revision") is not None else 0,
            "metadata": AgentMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None
        })
        return _obj


