# coding: utf-8

# flake8: noqa
"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from almanac.models.address_prefix import AddressPrefix
from almanac.models.agent import Agent
from almanac.models.agent_endpoint import AgentEndpoint
from almanac.models.agent_name_availability import AgentNameAvailability
from almanac.models.agent_name_availability_status import AgentNameAvailabilityStatus
from almanac.models.agent_record import AgentRecord
from almanac.models.agent_registration_attestation import AgentRegistrationAttestation
from almanac.models.agent_registration_attestation_batch import AgentRegistrationAttestationBatch
from almanac.models.agent_registration_attestation_metadata_value import AgentRegistrationAttestationMetadataValue
from almanac.models.agent_status import AgentStatus
from almanac.models.agent_status_update import AgentStatusUpdate
from almanac.models.agent_type import AgentType
from almanac.models.developer_category import DeveloperCategory
from almanac.models.domain_record import DomainRecord
from almanac.models.endpoint_input import EndpointInput
from almanac.models.endpoint_output import EndpointOutput
from almanac.models.http_validation_error import HTTPValidationError
from almanac.models.interaction import Interaction
from almanac.models.interaction_type import InteractionType
from almanac.models.location_inner import LocationInner
from almanac.models.manifest import Manifest
from almanac.models.metadata import Metadata
from almanac.models.model import Model
from almanac.models.resolved_protocol_digest import ResolvedProtocolDigest
from almanac.models.service_record import ServiceRecord
from almanac.models.validation_error import ValidationError
