# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_clients.search_api.models.agent_category import AgentCategory

class TestAgentCategory(unittest.TestCase):
    """AgentCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgentCategory(self):
        """Test AgentCategory"""
        # inst = AgentCategory()

if __name__ == '__main__':
    unittest.main()
