# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_clients.search_api.models.function_type import FunctionType

class TestFunctionType(unittest.TestCase):
    """FunctionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFunctionType(self):
        """Test FunctionType"""
        # inst = FunctionType()

if __name__ == '__main__':
    unittest.main()
