# coding: utf-8

"""
    Agent Hosting API

      ## Overview  The Agent Hosting API helps users deploy agents to the cloud  ## Authentication  The entire API requires that the user authenticate with the ecosystem first before accessing the api 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.hosting.aio.api.hosting_v2_api import HostingV2Api


class TestHostingV2Api(unittest.IsolatedAsyncioTestCase):
    """HostingV2Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = HostingV2Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_agent_readiness_probe_v2(self) -> None:
        """Test case for agent_readiness_probe_v2

        Agent Readiness Probe
        """
        pass

    async def test_create_hosted_agent_v2(self) -> None:
        """Test case for create_hosted_agent_v2

        Create Hosted Agent
        """
        pass

    async def test_delete_agent_logs_v2(self) -> None:
        """Test case for delete_agent_logs_v2

        Delete Agent Logs
        """
        pass

    async def test_delete_agent_secret_v2(self) -> None:
        """Test case for delete_agent_secret_v2

        Delete Secret Endpoint
        """
        pass

    async def test_delete_agent_storage_v2(self) -> None:
        """Test case for delete_agent_storage_v2

        Delete Storage
        """
        pass

    async def test_delete_hosted_agent_v2(self) -> None:
        """Test case for delete_hosted_agent_v2

        Delete Agent
        """
        pass

    async def test_get_agent_code_v2(self) -> None:
        """Test case for get_agent_code_v2

        Get Code
        """
        pass

    async def test_get_agent_logs_v2(self) -> None:
        """Test case for get_agent_logs_v2

        Get Agent Logs
        """
        pass

    async def test_get_agent_secrets_v2(self) -> None:
        """Test case for get_agent_secrets_v2

        Get Secrets
        """
        pass

    async def test_get_agent_storage_by_key_v2(self) -> None:
        """Test case for get_agent_storage_by_key_v2

        Get Storage By Key
        """
        pass

    async def test_get_agent_storage_v2(self) -> None:
        """Test case for get_agent_storage_v2

        Get Storage
        """
        pass

    async def test_get_all_user_secrets_v2(self) -> None:
        """Test case for get_all_user_secrets_v2

        Get All Secrets
        """
        pass

    async def test_get_all_user_storage_v2(self) -> None:
        """Test case for get_all_user_storage_v2

        Get All Storage
        """
        pass

    async def test_get_hosted_agent_v2(self) -> None:
        """Test case for get_hosted_agent_v2

        Get Hosted Agent
        """
        pass

    async def test_get_specific_secret_v2(self) -> None:
        """Test case for get_specific_secret_v2

        Get Specific Secret
        """
        pass

    async def test_list_hosted_agents_v2(self) -> None:
        """Test case for list_hosted_agents_v2

        List Hosted Agents
        """
        pass

    async def test_start_hosted_agent_v2(self) -> None:
        """Test case for start_hosted_agent_v2

        Start Agent
        """
        pass

    async def test_stop_hosted_agent_v2(self) -> None:
        """Test case for stop_hosted_agent_v2

        Stop Agent
        """
        pass

    async def test_submit_message_envelope_v2(self) -> None:
        """Test case for submit_message_envelope_v2

        Submit Message Envelope
        """
        pass

    async def test_update_agent_code_v2(self) -> None:
        """Test case for update_agent_code_v2

        Update Code
        """
        pass

    async def test_update_agent_secret_v2(self) -> None:
        """Test case for update_agent_secret_v2

        Update Secret
        """
        pass

    async def test_update_agent_storage_v2(self) -> None:
        """Test case for update_agent_storage_v2

        Update Storage
        """
        pass


if __name__ == '__main__':
    unittest.main()
