# coding: utf-8

"""
    Agent Hosting API

      ## Overview  The Agent Hosting API helps users deploy agents to the cloud  ## Authentication  The entire API requires that the user authenticate with the ecosystem first before accessing the api 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.hosting.aio.models.agent_v1 import AgentV1

class TestAgentV1(unittest.TestCase):
    """AgentV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentV1:
        """Test AgentV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentV1`
        """
        model = AgentV1()
        if include_optional:
            return AgentV1(
                name = '',
                address = '',
                domain = '',
                prefix = 'agent',
                running = True,
                compiled = True,
                code_digest = '',
                wallet_address = '',
                code_update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                avatar_url = '',
                maintainer_id = '',
                revision = 56,
                readme = '',
                short_description = '',
                metadata = { }
            )
        else:
            return AgentV1(
                name = '',
                address = '',
                running = True,
                revision = 56,
        )
        """

    def testAgentV1(self):
        """Test AgentV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
