# coding: utf-8

"""
    Agent Hosting API

      ## Overview  The Agent Hosting API helps users deploy agents to the cloud  ## Authentication  The entire API requires that the user authenticate with the ecosystem first before accessing the api 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.hosting.aio.models.with_pagination_agent_summary_v1 import WithPaginationAgentSummaryV1

class TestWithPaginationAgentSummaryV1(unittest.TestCase):
    """WithPaginationAgentSummaryV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WithPaginationAgentSummaryV1:
        """Test WithPaginationAgentSummaryV1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WithPaginationAgentSummaryV1`
        """
        model = WithPaginationAgentSummaryV1()
        if include_optional:
            return WithPaginationAgentSummaryV1(
                items = [
                    agentverse_client.hosting.aio.models.agent_summary_v1.AgentSummaryV1(
                        name = '', 
                        address = '', 
                        domain = '', 
                        prefix = 'agent', 
                        running = True, 
                        compiled = True, 
                        code_digest = '', 
                        wallet_address = '', 
                        code_update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        avatar_url = '', )
                    ],
                next_cursor = ''
            )
        else:
            return WithPaginationAgentSummaryV1(
                items = [
                    agentverse_client.hosting.aio.models.agent_summary_v1.AgentSummaryV1(
                        name = '', 
                        address = '', 
                        domain = '', 
                        prefix = 'agent', 
                        running = True, 
                        compiled = True, 
                        code_digest = '', 
                        wallet_address = '', 
                        code_update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        creation_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        avatar_url = '', )
                    ],
        )
        """

    def testWithPaginationAgentSummaryV1(self):
        """Test WithPaginationAgentSummaryV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
