# coding: utf-8

"""
    FastAPI

    An API for our smart search engine that provides the agent that best fits your needs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.search.aio.api.agents_api import AgentsApi


class TestAgentsApi(unittest.IsolatedAsyncioTestCase):
    """AgentsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AgentsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_feedback(self) -> None:
        """Test case for feedback

        Feedback
        """
        pass

    async def test_get_agent_interactions_count(self) -> None:
        """Test case for get_agent_interactions_count

        Get Interaction Counts Of Agent
        """
        pass

    async def test_get_recent_agent_interactions(self) -> None:
        """Test case for get_recent_agent_interactions

        Get Recent Agent Asi1 Interactions
        """
        pass

    async def test_search_agent_by_geolocation(self) -> None:
        """Test case for search_agent_by_geolocation

        Search Agent By Geolocation
        """
        pass

    async def test_search_agent_tags(self) -> None:
        """Test case for search_agent_tags

        Search Agent Tags
        """
        pass

    async def test_search_agents(self) -> None:
        """Test case for search_agents

        Search Agents
        """
        pass

    async def test_search_agents_by_similarity(self) -> None:
        """Test case for search_agents_by_similarity

        Search Agents By Similarity
        """
        pass

    async def test_start_seo_eval(self) -> None:
        """Test case for start_seo_eval

        Start Seo Eval
        """
        pass


if __name__ == '__main__':
    unittest.main()
