# coding: utf-8

"""
    FastAPI

    An API for our smart search engine that provides the agent that best fits your needs.

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.search.aio.api.search_api import SearchApi


class TestSearchApi(unittest.IsolatedAsyncioTestCase):
    """SearchApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = SearchApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_feedback(self) -> None:
        """Test case for feedback

        Feedback
        """
        pass

    async def test_get_agent_insights(self) -> None:
        """Test case for get_agent_insights

        Get Agent Insights
        """
        pass

    async def test_get_agent_search_terms_analytics(self) -> None:
        """Test case for get_agent_search_terms_analytics

        Get Agent Search Term Analytics
        """
        pass

    async def test_get_agent_searches_analytics(self) -> None:
        """Test case for get_agent_searches_analytics

        Get Agent Search Analytics
        """
        pass

    async def test_get_analytics_summary(self) -> None:
        """Test case for get_analytics_summary

        Get Analytics Summary
        """
        pass

    async def test_get_function_interactions(self) -> None:
        """Test case for get_function_interactions

        Get Recent Interactions Of Function
        """
        pass

    async def test_search_agents(self) -> None:
        """Test case for search_agents

        Search Agents
        """
        pass

    async def test_search_functions(self) -> None:
        """Test case for search_functions

        Search Functions
        """
        pass


if __name__ == '__main__':
    unittest.main()
