# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_clients.search.models.net_protocol import NetProtocol

class TestNetProtocol(unittest.TestCase):
    """NetProtocol unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNetProtocol(self):
        """Test NetProtocol"""
        # inst = NetProtocol()

if __name__ == '__main__':
    unittest.main()
