# coding: utf-8

"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.almanac.api.almanac_v2_api import AlmanacV2Api


class TestAlmanacV2Api(unittest.TestCase):
    """AlmanacV2Api unit test stubs"""

    def setUp(self) -> None:
        self.api = AlmanacV2Api()

    def tearDown(self) -> None:
        pass

    def test_check_handle_availability_v2(self) -> None:
        """Test case for check_handle_availability_v2

        Check Handle Availability V2
        """
        pass

    def test_generate_handle_v2(self) -> None:
        """Test case for generate_handle_v2

        Generate Handle V2
        """
        pass

    def test_get_manifest_by_name_v2(self) -> None:
        """Test case for get_manifest_by_name_v2

        Get Manifest By Name V2
        """
        pass

    def test_get_manifest_v2(self) -> None:
        """Test case for get_manifest_v2

        Get Manifest V2
        """
        pass

    def test_get_protocol_model_v2(self) -> None:
        """Test case for get_protocol_model_v2

        Get Protocol Model V2
        """
        pass

    def test_resolve_identifier_v2(self) -> None:
        """Test case for resolve_identifier_v2

        Resolve Identifier V2
        """
        pass

    def test_upload_manifest_v2(self) -> None:
        """Test case for upload_manifest_v2

        Upload Manifest V2
        """
        pass


if __name__ == '__main__':
    unittest.main()
