# coding: utf-8

"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.almanac.models.new_handle_request import NewHandleRequest

class TestNewHandleRequest(unittest.TestCase):
    """NewHandleRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NewHandleRequest:
        """Test NewHandleRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NewHandleRequest`
        """
        model = NewHandleRequest()
        if include_optional:
            return NewHandleRequest(
                agent_address = '',
                handle = ''
            )
        else:
            return NewHandleRequest(
                agent_address = '',
                handle = '',
        )
        """

    def testNewHandleRequest(self):
        """Test NewHandleRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
