# coding: utf-8

"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.almanac.models.handle_availability_response import HandleAvailabilityResponse

class TestHandleAvailabilityResponse(unittest.TestCase):
    """HandleAvailabilityResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HandleAvailabilityResponse:
        """Test HandleAvailabilityResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HandleAvailabilityResponse`
        """
        model = HandleAvailabilityResponse()
        if include_optional:
            return HandleAvailabilityResponse(
                available = True,
                handle = '',
                alternative = ''
            )
        else:
            return HandleAvailabilityResponse(
                available = True,
                handle = '',
        )
        """

    def testHandleAvailabilityResponse(self):
        """Test HandleAvailabilityResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
