# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.almanac.aio.api.almanac_api import AlmanacApi


class TestAlmanacApi(unittest.IsolatedAsyncioTestCase):
    """AlmanacApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = AlmanacApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_agents_by_domain_v1_almanac_search_agents_by_domain_domain_name_get(self) -> None:
        """Test case for get_agents_by_domain_v1_almanac_search_agents_by_domain_domain_name_get

        Get Agents By Domain
        """
        pass

    async def test_get_domain_details_v1_almanac_search_domain_details_domain_name_get(self) -> None:
        """Test case for get_domain_details_v1_almanac_search_domain_details_domain_name_get

        Get Domain Details
        """
        pass

    async def test_get_domain_record_v1_almanac_domains_domain_get(self) -> None:
        """Test case for get_domain_record_v1_almanac_domains_domain_get

        Get Domain Record
        """
        pass

    async def test_get_domains_v1_almanac_search_domains_address_get(self) -> None:
        """Test case for get_domains_v1_almanac_search_domains_address_get

        Get Domains
        """
        pass

    async def test_get_recently_registered_agents_v1_almanac_recent_get(self) -> None:
        """Test case for get_recently_registered_agents_v1_almanac_recent_get

        Get Recently Registered Agents
        """
        pass

    async def test_get_specific_agent_v1_almanac_agents_address_get(self) -> None:
        """Test case for get_specific_agent_v1_almanac_agents_address_get

        Get Specific Agent
        """
        pass

    async def test_register_agent_v1_almanac_agents_post(self) -> None:
        """Test case for register_agent_v1_almanac_agents_post

        Register Agent
        """
        pass

    async def test_register_agents_batch_v1_almanac_agents_batch_post(self) -> None:
        """Test case for register_agents_batch_v1_almanac_agents_batch_post

        Register Agents Batch
        """
        pass

    async def test_search_agents_v1_almanac_search_post(self) -> None:
        """Test case for search_agents_v1_almanac_search_post

        Search Agents
        """
        pass

    async def test_search_available_agent_name_v1_almanac_search_available_name_get(self) -> None:
        """Test case for search_available_agent_name_v1_almanac_search_available_name_get

        Search Available Agent Name
        """
        pass

    async def test_update_agent_status_v1_almanac_agents_agent_address_status_post(self) -> None:
        """Test case for update_agent_status_v1_almanac_agents_agent_address_status_post

        Update Agent Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
