# coding: utf-8

"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.almanac.aio.models.almanac_usage import AlmanacUsage

class TestAlmanacUsage(unittest.TestCase):
    """AlmanacUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlmanacUsage:
        """Test AlmanacUsage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlmanacUsage`
        """
        model = AlmanacUsage()
        if include_optional:
            return AlmanacUsage(
                num_domains = 56,
                max_domains = 56
            )
        else:
            return AlmanacUsage(
        )
        """

    def testAlmanacUsage(self):
        """Test AlmanacUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
