# coding: utf-8

"""
    FastAPI

    A simple fastapi application that services registered agents information

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentverse_client.almanac.aio.api.usage_api import UsageApi


class TestUsageApi(unittest.IsolatedAsyncioTestCase):
    """UsageApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UsageApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_user_usage(self) -> None:
        """Test case for get_user_usage

        Get User Usage
        """
        pass


if __name__ == '__main__':
    unittest.main()
