name: Receive Documentation

on:
  repository_dispatch:
    types: [send-docs]

permissions:
  contents: write

jobs:
  process-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Receive and Persist JSON OpenAPI specs
        env:
          AUTHOR: ${{ github.event.client_payload.author }}
          OPENAPI_COMPRESSED: ${{ github.event.client_payload.file_content_base_64 }}
          APP_NAME: ${{ github.event.client_payload.app_name }}
          WEB_OPENAPI_PATH: ${{ github.workspace }}/src/web/openapi_specs
        run: |
          author=$GITHUB_AUTHOR
          echo "::notice:: Process triggered by $AUTHOR"
          
          # Replace - by _ in order to avoid some errors at generating packages.
          APP_NAME=$(echo $APP_NAME | sed s/-/_/g)
          if [[ $APP_NAME == "" ]]; then
            echo "::error:: APP_NAME cannot be empty"
            exit 1
          fi
          openapi_filename="$APP_NAME"_openapi_specification.json
          openapi_filepath=$WEB_OPENAPI_PATH/$openapi_filename
          echo "Persisting openapi specs  in $openapi_filepath" 
          OPENAPI=$(echo $OPENAPI_COMPRESSED | base64 -d | unxz -c)
          echo $OPENAPI > $openapi_filepath
          echo "----"
          
          echo "API_ROOT_DIR=${{ github.workspace }}/src/apis" >> $GITHUB_ENV
          echo "CLIENT_ROOT_DIR=${{ github.workspace }}/src/agentverse-clients" >> $GITHUB_ENV
          
          echo "::notice::Update for $APP_NAME"

          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "openapi_filepath=$openapi_filepath" >> $GITHUB_ENV
          echo "openapi_filename=$openapi_filename" >> $GITHUB_ENV

      - name: Check registered apps and get client path

        run: |
          app_key=${{ github.event.client_payload.app_name }}
          registered_apps=${{ vars.APP_MAPPING }}
          echo "::notice:: $registered_apps"
          echo $registered_apps
          # decode
          registered_apps=$(echo $registered_apps | xxd -r -p)
          # get path from json
          client_path=$(echo $registered_apps | jq -c '.["'$app_key'"]')
          echo $registered_apps
          echo $client_path
          echo $APP_NAME
          echo '.["'$APP_NAME'"]'
          if [ $client_path = "null" ]
          then
            exit 1
          else
            echo "CLIENT_PATH=$client_path" >> $GITHUB_ENV
          fi
      - name: Create scaffolding & register docs
        run: |
          echo "API_ROOT_DIR: $API_ROOT_DIR"
          
          # TODO: What to do with conflict?
          if [ ! -d $API_ROOT_DIR/$APP_NAME ]
          then
            echo "::notice:: Creating dir $API_ROOT_DIR/$APP_NAME"
            mkdir $API_ROOT_DIR/$APP_NAME
          else
            echo "API $API_ROOT_DIR/$APP_NAME already exists."
          fi
          
          # Add file to register docs into fastapi 
          cat <<- EOF > $API_ROOT_DIR/$APP_NAME/register_api_docs.py
          api_id: str = '$APP_NAME'
          openapi_specs_name: str = '$openapi_filename'
          docs_endpoint_name: str = '/$APP_NAME/'
          EOF

      - name: Prepare openapi config file
        env:
          CLIENT_ROOT_PROJECT_NAME: "agentverse_clients"
        run: |
          config_file_path="./generator_config_file.yaml"
          
          # CONFIG FILE DEFINITION
          cat <<- EOF -> $config_file_path
          generatorName: python
          inputSpec: $openapi_filepath
          additionalProperties:
            packageName: $CLIENT_ROOT_PROJECT_NAME.$CLIENT_PATH
            projectName: $APP_NAME
            generateSourceCodeOnly: true
          configOptions:
            packageVersion: "1.0.0"
            library: fastapi
          EOF
          
          cat $config_file_path
          
          echo "config_file_path=$config_file_path" >> $GITHUB_ENV
          echo $OPENAPI > ./openapi.json
          
      - name: Generate client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: python
          config-file: ${{ env.config_file_path }}
          openapi-file: ./src/web/openapi_specs/${{ env.openapi_filename }}
          command-args: "-o ./src/agentverse-clients"

      - name: Persist changes with Git
        run: |
          echo "Commiting dir $API_ROOT_DIR/$APP_NAME"
          git config --local user.name "fetchbot"
          git config --local user.email "fetchbot@fetch.ai"
          git add $API_ROOT_DIR/$APP_NAME ${{ github.workspace }}/src/web/ ${{ env.CLIENT_ROOT_DIR }}
          git commit -m "Adding or updating docs and client for $APP_NAME" || echo "No changes to commit"
          git push
